### ISSUE TITLE
Setup CI/CD for supervisor

### ISSUE THREAD

**Issue by anmolbabu** [fabric8-hypothesis/fabric8-hypothesis-planning#1]
- [x] Jenkins    --   @anmolbabu

- [x] UTs and Initial commit with basic endpoint that echoes the metric passed to it -- @anmolbabu

- [x] CICO 
  - cico_build_deploy.sh and cico_setup.sh -- @anmolbabu
  - cico_run_pylint.sh
  - cico_run_tests.sh -- @dev-gaur

**Comment by devang-gaur** [comment]
Hey guys, If we're running good on the minishift setup ( I think we are! ), then its the right time to request for a Dev-Cluster to the Service Delivery team.

Some pre-requisites :

1.) Our docker images must be listed in the following index : https://github.com/CentOS/container-index
This is the index which maintains, registry.centos.org .
Therefore, we need to follow the guide provided in the repository and make the required modifications.

2.) To request for the Dev-Cluster we need to provide them a document regarding our specifications, requirements and other related stuff.

**Comment by anmolbabu** [comment]
Closing this as it has been completed
